LAYAIraq/LAYA-Iraq-Frontend

- src/store/index.ts
- src/store/modules/auth.ts
- src/store/modules/password.ts
- src/store/modules/profile.ts
- src/store/modules/users.ts
- src/views/admin-panel.vue
- src/views/pwd-reset.vue
Moved password methods to own store module.
What to test:
> Password store module

- src/i18n/de.json
- src/i18n/en.json
- src/views/login.vue
> added modal to confirm password reset

- src/components/authoring/course-create.vue
- src/components/header.vue
- src/components/ly-course-list.vue
- src/plugins/laya-la-drag-drop/common-methods.ts
- src/plugins/laya-la-drag-drop/create.vue
- src/plugins/laya-la-drag-drop/edit.vue
- src/plugins/laya-la-drag-drop/view.vue
- src/plugins/laya-la-relate/common-methods.ts
- src/plugins/laya-la-relate/create.vue
- src/plugins/laya-la-relate/edit.vue
- src/plugins/laya-la-relate/view.vue
- src/store/modules/auth.ts
> Refactors april 22

- package-lock.json
- package.json
- src/components/ly-course-list.vue
- src/main.ts
- src/plugins/laya-la-relate/view.vue
- src/plugins/laya-lb-dialog/view.vue
- src/plugins/misc/laya-upload-file-list/file-list.vue
Added Authoritation headers for file upload requests for realizing ACLs in backend.
> added authorization headers to file-list.vue

- src/views/course-edit-tools/course-delete-block.vue
- tests/unit/views/course-edit-tools/course-delete-block.spec.ts
Added test for CourseDeleteBlock, fixed render issue
> added course-delete-block.spec.ts

- src/views/course-edit-tools/course-rename.vue
- tests/unit/views/course-edit-tools/course-rename.spec.ts
Tests fail because component doesn't work as expected
> added course-rename.spec.ts

- CHANGELOG
- package.json
- src/plugins/laya-la-drag-drop/view.vue
- src/plugins/laya-la-scmc/choices-common-methods.ts
- src/plugins/laya-la-scmc/create.vue
- src/plugins/laya-la-scmc/edit.vue
- src/plugins/laya-la-scmc/view.vue
Moved version number up, created new entry in CHANGELOG
> Renamed working branch to dev/sprint, finish sprint 4

- tests/unit/views/course-edit-tools/course-change-category.spec.ts
Test updated for compability. Tests fail b/c component doesn't match the tested criteria
> TLI-127 reviewed test

- src/i18n/en.json
- src/plugins/laya-la-feedback/create.vue
- src/plugins/laya-la-feedback/edit.vue
- src/plugins/laya-la-feedback/view.vue
- src/store/modules/enrollment.ts
- src/views/course-edit-tools/course-feedback-download.vue
This branch contains some fixes in dealing with course feedback. It should:
> Addressing some issues in feedback feature

- src/views/admin-panel.vue
- tests/template.spec.ts
- tests/unit/views/admin-panel.spec.ts
> Create Test Template, AdminPanel Test Skeleton

- src/components/course/course-edit/course-preferences.vue
> TLI-463 save-settings-in-author-tool-doesnt-give-feedback 

- src/assets/i18n/en.json
- src/plugins/learning-assessment/image-matching/image-matching-edit.vue
please check if it looks alright
> TLI-454 button-for-add-content-in-image-matching-edit-placed-wrongly

- src/plugins/learning-block/video-player/video-edit.vue
please check out new mobile friendly add captions table
> TLI-451 plugin-video-needs-dynamic-column

- src/assets/i18n/en.json
- src/components/helpers/content-task-edit.vue
- src/components/helpers/content-title-edit.vue
- src/plugins/learning-assessment/category-matching/category-matching-edit.vue
- src/plugins/learning-assessment/choice-question/choice-question-edit.vue
- src/plugins/learning-assessment/image-matching/image-matching-edit.vue
- src/plugins/organization/button-navigation/button-navigation-edit.vue
- src/plugins/organization/feedback/feedback-edit.vue
moved task to new component, and added warning if simple language field is not filled
> TLI-428 add-warning-if-simple-language-field-is-not-filled 

- src/plugins/learning-assessment/image-matching/image-matching-view.vue
> TLI-524 remove-remove-choices-from-image-matching-(audit)

- src/components/course/course-edit/course-preferences.vue
- src/components/course/course-list/course-create.vue
- src/components/general/header.vue
- src/components/notifications/header-notifications.vue
- src/components/user-views/profile.vue
icons now added for cohesiveness
> TLI-5427 icon-for-Save-Button-not-displayed-in-Author-tool-(check-for-all-icons)

- src/components/user-views/admin-panel.vue
- src/plugins/learning-block/video-player/video-edit.vue
admin panel is now responsive table
> TLI-446 expand-column-for-email-verified-in-admin-tool

- src/store/modules/profile.ts
- src/store/modules/register.ts
emails now get converted to lower case in store methods before http requests
> TLI-419 ignore-case-in-email

- src/plugins/organization/button-navigation/button-navigation-edit.vue
- src/plugins/organization/button-navigation/button-navigation-view.vue
button navigation buttons now look more cohesive
> TLI-304 button-navigation-fix-button-size-and-display

- src/components/user-views/admin-panel.vue
fixed admin panel filtering behaviour
> TLI-147 admin-panel-filtering-roles-does-not-work

- src/components/course/course-edit/course-abstract-change.vue
- src/components/course/course-edit/course-authorname-change.vue
- src/components/course/course-edit/course-category-change.vue
- src/components/course/course-edit/course-keywords-change.vue
- src/components/course/course-edit/course-language-change.vue
- src/components/course/course-edit/course-rename.vue
- src/components/user-views/admin-panel.vue
modals in course edit and admin panel now react upon enter key
> Dev/tli 176 course rename doesn't fire when pressing enter in input field

- src/mixins/vue/list-sort.ts
lists now sort for every possible filter
> TLI-195 fix-list-sort-for-names-in-file-list

- src/components/course/course-list/course-list-details.vue
new course list as responsive table, and start as a button
> Dev/tli 516 course list table (audit)

- src/components/general/login.vue
- src/components/general/register.vue
- src/components/helpers/password-input.vue
- src/components/user-views/profile.vue
- src/plugins/learning-assessment/category-matching/category-matching-view.vue
- src/plugins/learning-assessment/image-matching/image-matching-view.vue
- src/plugins/organization/feedback/feedback-view.vue
> Dev/tli 535 labels (audit)

- src/components/course/course-edit/course-block-edit.vue
- src/components/course/course-edit/course-feedback-download.vue
- src/components/course/course-edit/course-nav-edit.vue
- src/components/course/course-edit/course-rename.vue
- src/components/course/course-list/course-create.vue
- src/components/course/course-list/course-list-details.vue
- src/components/course/course-list/course-list.vue
- src/components/general/header.vue
- src/components/general/login.vue
- src/components/general/register.vue
- src/components/helpers/password-input.vue
- src/components/helpers/upload-file.vue
- src/components/notifications/header-notifications.vue
- src/components/notifications/notifications.vue
- src/plugins/learning-assessment/category-matching/category-matching-edit.vue
- src/plugins/learning-assessment/category-matching/category-matching-view.vue
- src/plugins/learning-assessment/choice-question/choice-question-edit.vue
- src/plugins/learning-assessment/choice-question/choice-question-view.vue
- src/plugins/learning-assessment/image-matching/image-matching-edit.vue
- src/plugins/learning-assessment/image-matching/image-matching-view.vue
- src/plugins/learning-block/free-text/free-text-view.vue
- src/plugins/organization/button-navigation/button-navigation-edit.vue
- src/plugins/organization/feedback/feedback-edit.vue
- src/plugins/organization/feedback/feedback-view.vue
see audit for details
merge after labels
> TLI-534 aria labels (audit)

- src/App.vue
- src/components/course/course-list/course-list.vue
- src/components/general/footer.vue
- src/components/general/header.vue
- src/components/general/login.vue
- src/components/general/register.vue
> Dev/tli 533 alt text (audit)

- src/assets/styles/color-correction.css
- src/components/general/header.vue
> TLI-538 changed the colors according to audit

- src/components/course/course-list/course-list.vue
- src/components/course/course.vue
- src/components/course/flag/flag.vue
- src/components/general/header.vue
- src/components/general/imprint.vue
- src/components/general/landing-page.vue
- src/components/general/login.vue
- src/components/general/not-found.vue
- src/components/general/privacy.vue
- src/components/general/register.vue
- src/components/user-views/admin-panel.vue
- src/components/user-views/editor-panel.vue
- src/components/user-views/profile.vue
please read jira comment beforehand
> TLI-517 changed header into one nav bar and added header tag

- src/components/course/course-edit/course-preferences.vue
> TLI-129 simple-language-selection-check-persists-when-creating-new-courses 
